server.port=8081
spring.application.name=stablematch-service

# Actuator Configuration
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.metrics.tags.application=${spring.application.name}

# Eureka Configuration (Va fi folosit la pasul 3)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/